Iterating on Moderne CLI download

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -14,6 +14,13 @@ inputs:
   github_token:
     description: 'GitHub Personal Access Token for authentication'
     required: true
+  moderne_cli_version:
+    description: 'Specific version of the Moderne CLI to use (e.g. 3.51.2)'
+    required: false
+  moderne_cli_stage:
+    description: 'Stage of the Moderne CLI to use (stable or staging)'
+    required: false
+    default: 'stable'
 runs:
   using: "composite"
   steps:
@@ -25,10 +32,38 @@ runs:
 
     - name: Install Moderne CLI
       shell: bash
+      env:
+        MODERNE_CLI_VERSION: ${{ inputs.moderne_cli_version }}
+        MODERNE_CLI_STAGE: ${{ inputs.moderne_cli_stage }}
       run: |
-        curl -sL https://github.com/moderneinc/moderne-cli/releases/latest/download/mod-linux-x64 -o mod
-        chmod +x mod
-        sudo mv mod /usr/local/bin/
+        # Download the specified version of moderne-cli JAR file if MODERNE_CLI_VERSION is provided,
+        # otherwise download the latest version
+        if [ -n "${MODERNE_CLI_VERSION}" ]; then \
+            echo "Downloading version: ${MODERNE_CLI_VERSION}"; \
+            curl -s --insecure --request GET --url "https://repo1.maven.org/maven2/io/moderne/moderne-cli/${MODERNE_CLI_VERSION}/moderne-cli-${MODERNE_CLI_VERSION}.jar" --output /usr/local/bin/mod.jar; \
+        elif [ "${MODERNE_CLI_STAGE}" == "staging" ]; then \
+            LATEST_VERSION=$(curl -s --insecure --request GET --url "https://api.github.com/repos/moderneinc/moderne-cli-releases/releases" | jq '.[0].tag_name' -r | sed "s/^v//"); \
+            if [ -z "${LATEST_VERSION}" ]; then \
+                echo "Failed to get latest staging version"; \
+                exit 1; \
+            fi; \
+            echo "Downloading latest staging version: ${LATEST_VERSION}"; \
+            curl -s --insecure --request GET --url "https://repo1.maven.org/maven2/io/moderne/moderne-cli/${LATEST_VERSION}/moderne-cli-${LATEST_VERSION}.jar" --output /usr/local/bin/mod.jar; \
+        else \
+            LATEST_VERSION=$(curl -s --insecure --request GET --url "https://api.github.com/repos/moderneinc/moderne-cli-releases/releases/latest" | jq '.tag_name' -r | sed "s/^v//"); \
+            if [ -z "${LATEST_VERSION}" ]; then \
+                echo "Failed to get latest stable version"; \
+                exit 1; \
+            fi; \
+            echo "Downloading latest stable version: ${LATEST_VERSION}"; \
+            curl -s --insecure --request GET --url "https://repo1.maven.org/maven2/io/moderne/moderne-cli/${LATEST_VERSION}/moderne-cli-${LATEST_VERSION}.jar" --output /usr/local/bin/mod.jar; \
+        fi
+
+        # Create a shell script 'mod' that runs the moderne-cli JAR file
+        echo -e '#!/bin/sh\njava -jar /usr/local/bin/mod.jar "$@"' > /usr/local/bin/mod
+
+        # Make the 'mod' script executable
+        chmod +x /usr/local/bin/mod
 
     - name: Run Sync Script
       shell: bash
